export {default as Header} from './header'
export {default as Categories} from './categories'
export {default as Button} from './button'
export {default as SortPizza} from './sortPizza'
export {default as CartItem} from './cartItem'
 export {default as PizzaBlock} from './PizzaBlock/index'
 export {default as LoadingBlock} from './PizzaBlock/LoadingBlock'
// export {default as Pizzablocks} from './PizzaBlock'
// export {default as LoadingBlock} from './PizzaBlock/LoadingBlock'